version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  # Backend application service
  backend-app:
    build: ./backend  # Build context for the backend app
    image: tocos-backend:latest
    container_name: tocos-backend
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: test
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/tocos  # MongoDB connection URI
      MONGO_TEST_URI: mongodb://mongo:27017/test_tocos  # MongoDB test connection URI
    depends_on:
      - mongo  # Ensure that the backend app starts after the MongoDB service
    restart: on-failure

  # Frontend application service
  frontend-app:
    build: ./frontend  # Build context for the frontend app
    image: tocos-frontend:latest
    container_name: tocos-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend-app  # Ensure that the frontend app starts after the backend app
    restart: on-failure

volumes:
  mongodb_data_container:  # Persistent volume for MongoDB data