version: '3.8'

services:
  mongo:
    image: mongo:latest
    expose:
      -27017
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: test
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/tocos
      MONGO_TEST_URI: mongodb://mongo:27017/test_tocos
    depends_on:
      - mongo
    restart: on-failure
    links:
      - "mongo:mongodb"

volumes:
  mongodb_data_container: